// Parity test: the JS engine must reproduce the canonical Python core's analytics.
// golden.json is generated by tools/gen_golden.py from Garminimax's core/; this
// runs the JS port over the same inputs and asserts equality. Run: node --test
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { computeTrainingLoad } from "../engine/pmc.mjs";
import { computeCoachState } from "../engine/coachState.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const GOLDEN = JSON.parse(readFileSync(join(HERE, "golden.json"), "utf8"));

// Numeric fidelity, tolerant of Python round-half-even vs JS round-half-up at the
// last decimal (the underlying math must match; a 0.05/0.005 gap is a rounding edge).
const near = (a, b, tol) => {
  if (a == null || b == null) return a === b;
  return Math.abs(a - b) <= tol;
};

for (const c of GOLDEN.cases) {
  const { activities, athlete, as_of, wellness } = c.input;

  test(`training_load: ${c.name}`, () => {
    const tl = computeTrainingLoad(activities, athlete, { asOf: as_of });
    const exp = c.training_load;
    assert.equal(tl.unit, exp.unit, "unit");
    assert.deepEqual(tl.needs.sort(), [...exp.needs].sort(), "needs");
    assert.deepEqual(tl.coverage, exp.coverage, "coverage");
    assert.equal(tl.series.length, exp.series.length, "series length");
    tl.series.forEach((d, i) => {
      const e = exp.series[i];
      assert.equal(d.date, e.date, `series[${i}].date`);
      for (const k of ["load", "ctl", "atl", "tsb"]) {
        assert.ok(near(d[k], e[k], 0.05), `series[${i}].${k}: js ${d[k]} vs core ${e[k]}`);
      }
    });
  });

  test(`coach_state: ${c.name}`, () => {
    const cs = computeCoachState(activities, athlete, { asOf: as_of, wellness });
    const exp = c.coach_state;
    assert.equal(cs.history_days, exp.history_days, "history_days");
    assert.equal(cs.unit, exp.unit, "unit");
    assert.equal(cs.acwr_zone, exp.acwr_zone, "acwr_zone");
    assert.equal(cs.last_hard_date, exp.last_hard_date, "last_hard_date");
    assert.equal(cs.days_since_hard, exp.days_since_hard, "days_since_hard");
    for (const [k, tol] of [["ctl", 0.05], ["atl", 0.05], ["tsb", 0.05],
      ["ramp_rate", 0.05], ["acwr", 0.005], ["monotony", 0.01], ["strain", 1.0]]) {
      assert.ok(near(cs[k], exp[k], tol), `${k}: js ${cs[k]} vs core ${exp[k]}`);
    }
    // Readiness (present only when wellness supplied).
    if (exp.readiness == null) {
      assert.equal(cs.readiness, null, "readiness null");
    } else {
      assert.equal(cs.readiness.fresh, exp.readiness.fresh, "readiness.fresh");
      assert.ok(near(cs.readiness.rhr_delta, exp.readiness.rhr_delta, 0.05), "readiness.rhr_delta");
      assert.ok(near(cs.readiness.baseline_resting_hr, exp.readiness.baseline_resting_hr, 0.05), "readiness.baseline");
    }
  });
}
